<<<<<<< HEAD

print("ingrese las notas de Joel")
J1 = float(input("nota 1: "))
J2 = float(input("nota 2: "))
J3 = float(input("nota 3: "))
NM = (J1, J2, J3)
print("la nota minima es: ")
print(min(NM))
print("la nota maxima es: ")
print(max(NM))
prom1 = (J1 + J2 + J3)
prom12 = (prom1 / 3)
print('promedio Joel: ', round(prom12,3))

print("ingrese las notas de Alondra")
A1 = float(input("nota 1: "))
A2 = float(input("nota 2: "))
A3 = float(input("nota 3: "))
NM2 = (A1, A2, A3)
print("la nota minima es: ")
print(min(NM2))
print("la nota maxima es: ")
print(max(NM2))
prom2 = (A1 + A2 + A3)
prom22 = (prom2 / 3)
print('promedio Alondra: ', round(prom22,3))

print("ingrese las notas de Paz")
P1 = float(input("nota 1: "))
P2 = float(input("nota 2: "))
P3 = float(input("nota 3: "))
NM3 = (P1, P2, P3)
print("la nota minima es: ")
print(min(NM3))
print("la nota maxima es: ")
print(max(NM3))
prom3 = (P1 + P2 + P3)
prom32 = (prom3 / 3)
=======

print("ingrese las notas de Joel")
J1 = float(input("nota 1: "))
J2 = float(input("nota 2: "))
J3 = float(input("nota 3: "))
NM = (J1, J2, J3)
print("la nota minima es: ")
print(min(NM))
print("la nota maxima es: ")
print(max(NM))
prom1 = (J1 + J2 + J3)
prom12 = (prom1 / 3)
print('promedio Joel: ', round(prom12,3))

print("ingrese las notas de Alondra")
A1 = float(input("nota 1: "))
A2 = float(input("nota 2: "))
A3 = float(input("nota 3: "))
NM2 = (A1, A2, A3)
print("la nota minima es: ")
print(min(NM2))
print("la nota maxima es: ")
print(max(NM2))
prom2 = (A1 + A2 + A3)
prom22 = (prom2 / 3)
print('promedio Alondra: ', round(prom22,3))

print("ingrese las notas de Paz")
P1 = float(input("nota 1: "))
P2 = float(input("nota 2: "))
P3 = float(input("nota 3: "))
NM3 = (P1, P2, P3)
print("la nota minima es: ")
print(min(NM3))
print("la nota maxima es: ")
print(max(NM3))
prom3 = (P1 + P2 + P3)
prom32 = (prom3 / 3)
>>>>>>> 5e6f521c7616d906f61d8148c32c181955ff173b
print('promedio Paz: ', round(prom32,3))